name: Dispatch Modloader Updates

on:
  schedule:
    - cron: '0 0 * * 1'
    # - timezone: 'America/New_York' <- Not yet supported : https://github.com/github/roadmap/issues/1187
  workflow_dispatch:

permissions:
  actions: write

jobs:
  dispatch:
    name: Trigger modloader update on other branches
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - 1.20.1-NeoForge
          - 1.21.1-Fabric
          - 1.20.1-Fabric
    steps:
      - name: Trigger packwiz-update-modloader on ${{ matrix.branch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run packwiz-update-modloader.yml \
            --repo "${{ github.repository }}" \
            --ref "${{ matrix.branch }}"
